@startuml deployment
' skinparam linetype polyline
' skinparam linetype ortho

interface bt1
interface bt2
agent Detector1
agent Detector2

node RaspberryPi {
    database MainDb  {
        storage DetectorsData
    }
    frame OuterLayer {
        component Harvester <<D.M.Parker>>
        queue EventBus <<S.E.Brett>>
    }
    frame Main {
        component Core <<A.K.Dallas>>
        component TgBot <<MuThUr>>
    }
}

Main -[hidden]down- OuterLayer
Main -[hidden]up- MainDb
MainDb -[hidden]down-Main

Detector1 -> bt1
Harvester -> bt1

bt2 <- Detector2
Harvester -> bt2

Harvester -up-> EventBus
Core .> EventBus
Core .> MainDb
TgBot ~> EventBus
TgBot ~> MainDb

@enduml
